// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbwDHEL_NexCLnxXr2jT2Nsq6mZc5RjQI',
    appId: '1:840124773904:web:03ca7164f718524f4cfc95',
    messagingSenderId: '840124773904',
    projectId: 'flutter3-fca3e',
    authDomain: 'flutter3-fca3e.firebaseapp.com',
    databaseURL: 'https://flutter3-fca3e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter3-fca3e.appspot.com',
    measurementId: 'G-B49RJJW5S4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcRCx991TJCTfTfbSIILN7QrdfcGkswWY',
    appId: '1:840124773904:android:3e48ea6b645512a84cfc95',
    messagingSenderId: '840124773904',
    projectId: 'flutter3-fca3e',
    databaseURL: 'https://flutter3-fca3e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter3-fca3e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2l2WCTn09H7HjJxSPrEUQZd0-9SHMn6w',
    appId: '1:840124773904:ios:0ecf6ce63ee795d34cfc95',
    messagingSenderId: '840124773904',
    projectId: 'flutter3-fca3e',
    databaseURL: 'https://flutter3-fca3e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter3-fca3e.appspot.com',
    androidClientId: '840124773904-vjpe73cj77b8r9cruj9imoob4f47kjbv.apps.googleusercontent.com',
    iosClientId: '840124773904-e8mo4uf1phbfoguhuihf11o1c0v4mu1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.ytEcommerceAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2l2WCTn09H7HjJxSPrEUQZd0-9SHMn6w',
    appId: '1:840124773904:ios:0ecf6ce63ee795d34cfc95',
    messagingSenderId: '840124773904',
    projectId: 'flutter3-fca3e',
    databaseURL: 'https://flutter3-fca3e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter3-fca3e.appspot.com',
    androidClientId: '840124773904-vjpe73cj77b8r9cruj9imoob4f47kjbv.apps.googleusercontent.com',
    iosClientId: '840124773904-e8mo4uf1phbfoguhuihf11o1c0v4mu1d.apps.googleusercontent.com',
    iosBundleId: 'com.example.ytEcommerceAdminPanel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAu8LIjSuq08TVs7kwCnQdwD7SiMTRKi2I',
    appId: '1:840124773904:web:2b806ca73b9d7f924cfc95',
    messagingSenderId: '840124773904',
    projectId: 'flutter3-fca3e',
    authDomain: 'flutter3-fca3e.firebaseapp.com',
    databaseURL: 'https://flutter3-fca3e-default-rtdb.firebaseio.com',
    storageBucket: 'flutter3-fca3e.appspot.com',
    measurementId: 'G-2TKP13YSY3',
  );
}
